#-------------------------------
# General Site Settings
#-------------------------------
# Menu Section

menu:
  - {title: Home, url: '/'}
  - {title: Examples, url: '#examples'}
  - {title: Work, url: '/work/'}
  - {title: Contact, url: '#conect'}
#-------------------------------
# SEO Section

seo:
  twitter-creator: 'https://www.twitter.com/alanj2007games'
  twitter-site: 'https://www.twitter.com/alanj2007games'
  type: 'website'
  google-analytics: UA-xxxx-1

#-------------------------------
# About
about-text:
  header: ABOUT ME
  sub-header: Filmmaker . Director . Motion Designer .VFX Editor

about:
 - "I do PMVs, AMVs, random VFX videos, contents full of Motion Graphics, CC, and anything else that you can imagine from an editor. I have 7 years involvement in making visual effects and 2 years of motion designing. I separate them both so you wouldn't expect me to be so professional at everything."
 - "I utilize both of my different abilities to make an exceptional outcome, and I guarantee you this efficacy for the content that I'll be making for myself and the clients! I have worked with several people. I have done various commercial music videos, motion designing work throughout years and I do believe that I can do your required work as intended!"

#-------------------------------
# Examples
examples:
  - {video-id: qeTs05gFkT0}
  - {video-id: 7CJwb8FqaMs}
  - {video-id: e8wsfvgAG0A}
  - {video-id: tvvBZUwAcbo}
#-------------------------------
# Social Icons and URls

social:
  - {icon: 'fa-youtube-play', class: 'youtube-color youtube-color_border', url: 'https://www.youtube.com/AlanCrytex'}
  - {icon: 'fa-twitter', class: 'twitter-color twitter-color_border', url: 'https://twitter.com/Alanj2007Games'}

social-url:
  spotify: https://example.com

#-------------------------------
# Modified Date

modified-date: September 25, 2017

#-------------------------------
