#-------------------------------
# General Site Settings
#-------------------------------
# Menu Section

menu:
  - {title: Home, url: '/'}
  - {title: Examples, url: '#examples'}
  - {title: Work, url: '/work/'}
  - {title: Contact, url: '#contact'}

#-------------------------------
# SEO Section

seo:
  twitter-creator: '@alanj2007games'
  twitter-site: '@alanj2007games'
  type: 'website'
  google-analytics: UA-xxxx-1

#-------------------------------
# About
about-text:
  header: ABOUT ME
  sub-header: Filmmaker . Director . Motion Designer .VFX Editor

about:
 - 'Hello. I am a freelance VFX & Motion Graphics Artist and I have several years of experiences, working on personal projects and with clients.'
 - 'I mainly do lyric videos/music videos that are heavily containing Motion Graphics, Visual Effects and Typography. I do have a wide range of variation.'
 - 'I am trying my best to improve my work and making some videos that could entertain those who have followed me and for the clients I am working with!'

#-------------------------------
# Examples

examples:
  - {video-id: 5y7OYoBUYm4}
  - {video-id: Yj2kzgBri0s}
  - {video-id: PQVC68PC5Sk}
  - {video-id: x3WoE5XLFmo}

#-------------------------------
# works Gallery Section
# Filter

work_gallery-fliter:
- {title: 'All', name: 'all'}
- {title: 'Clients', name: 'clients'}
- {title: 'Personal ', name: 'personal'}

#Make sure  put images in the /img/work/thumbnails  folder.
work_gallery-work:
- {fliter: 'clients',  video-id: '5y7OYoBUYm4'}
- {fliter: 'personal',  video-id: 'PQVC68PC5Sk'}
- {fliter: 'personal',  video-id: 'DqP6lLupcdI'}
- {fliter: 'personal',  video-id: 'qeTs05gFkT0'}
- {fliter: 'clients',  video-id: 'x3WoE5XLFmo'}
- {fliter: 'clients',  video-id: 'mu0SXVGkiP4'}
- {fliter: 'clients',  video-id: 'MFHTw0XON5k'}
- {fliter: 'clients',  video-id: 'FSeDApAmvVY'}
- {fliter: 'clients',  video-id: 'Yj2kzgBri0s'}
- {fliter: 'personal',  video-id: 'pQN6LOOqJ7g'}
- {fliter: 'personal',  video-id: 'tvvBZUwAcbo'}
- {fliter: 'personal',  video-id: 'e8wsfvgAG0A'}
- {fliter: 'personal',  video-id: '7CJwb8FqaMs'}
- {fliter: 'personal',  video-id: '2VHgpHHtW_U'}

#------------------------------
# Contact

contact-header: Contact me

contact-name:
  data-error: Pleaase enter your name.
  placeholder: Name *

contact-email:
  data-error: Please make sure your email is either vaild or is filled in.
  placeholder: E-mail *

contact-packages-header: Which package do you want? (Prices are vary depending your approach)

contact-packages:
  - {checkbox-number: '1', spacing: spacing ,name: basic-videos-option, description: 'Basic Package - If you ever need subtitling, some text work or in general simpler effects for a music video, the price is $18 per min! or ($6/hr rate)', checked: checked }
  - {checkbox-number: '2', spacing: spacing ,name: advanced-videos-option, description: 'Advanced Package - I will be helping you produce a music video that is strongly based on some Motion Graphics, Typography, 3D Camera Work, Color Grading and much more. It can go up to $60 per min! or ($12/hr rate)', checked: }
  - {checkbox-number: '3', spacing:  ,name: baschorusc-videos-option, description: 'Chorus MV Package [Youtaite] - It would be on a fixed number which is $35 per min!', checked: }

contact-messages:
  name: Messages
  placeholder: Messages

#------------------------------
# Social Icons and URls

social:
  - {icon: 'fa-youtube-play', class: 'youtube-color youtube-color_border', url: 'https://www.youtube.com/AlanCrytex'}
  - {icon: 'fa-twitter', class: 'twitter-color twitter-color_border', url: 'https://twitter.com/Alanj2007Games'}

social-url:
  youtube: https://www.youtube.com/AlanCrytex
  twitter: https://twitter.com/Alanj2007Games
#-------------------------------
# Modified Date

modified-date: September 25, 2017

#-------------------------------
