#-------------------------------
# General Site Settings
#-------------------------------
# Menu Section

menu:
  - {title: Home, url: '#'}
  - {title: Examples, url: '#'}
  - {title: Work, url: '#'}
  - {title: Contact, url: '#'}
#-------------------------------
# SEO Section

seo:
  twitter-creator: 'https://www.twitter.com/alanj2007games'
  twitter-site: 'https://www.twitter.com/alanj2007games'
  type: 'website'
  google-analytics: UA-xxxx-1

#-------------------------------
# Social Icons and URls

social:
  - {icon: 'fa-youtube-play', color: 'youtube-color', url: 'https://www.youtube.com/AlanCrytex'}
  - {icon: 'fa-twitter', color: 'twitter-color', url: 'https://twitter.com/Alanj2007Games'}

social-url:
  spotify: https://example.com

#-------------------------------
# Modified Date

modified-date: September 25, 2017

#-------------------------------
