#-------------------------------
# General Site Settings
#-------------------------------
# Menu Section

menu:
  - {title: Home, url: '/'}
  - {title: Examples, url: '#examples'}
  - {title: Work, url: '/work/'}
  - {title: Contact, url: '#contact'}
#-------------------------------
# SEO Section

seo:
  twitter-creator: '@alanj2007games'
  twitter-site: '@alanj2007games'
  type: 'website'
  google-analytics: UA-xxxx-1

#-------------------------------
# About
about-text:
  header: ABOUT ME
  sub-header: Filmmaker . Director . Motion Designer .VFX Editor

about:
 - 'Hello. My name is Alan and I am known by the name. My full persona name is "Alan Crytex". I am a freelance VFX Editor and I have several years of experiences, working alone and with clients.'
 - 'My contents are heavily based on Motion Graphics and Live-Action and I tend to go onto random routes making some obscure videos.'
 - 'I am trying my best to improve my work and at the end produced some visually appealing projects for myself and for the clients who are interested working with me!'

#-------------------------------
# Examples

examples:
  - {video-id: qeTs05gFkT0}
  - {video-id: 7CJwb8FqaMs}
  - {video-id: e8wsfvgAG0A}
  - {video-id: tvvBZUwAcbo}

#-------------------------------
# works Gallery Section
# Filter

work_gallery-fliter:
- {title: 'All', name: 'all'}
- {title: 'Clients', name: 'clients'}
- {title: 'Personal ', name: 'personal'}

#Make sure  put images in the /img/work/thumbnails  folder.
work_gallery-work:
- {fliter: 'clients',  video-id: '5y7OYoBUYm4'}
- {fliter: 'clients',  video-id: 'FSeDApAmvVY'}
- {fliter: 'clients',  video-id: 'x3WoE5XLFmo'}
- {fliter: 'clients',  video-id: 'mu0SXVGkiP4'}
- {fliter: 'clients',  video-id: 'MFHTw0XON5k'}
- {fliter: 'clients',  video-id: 'Yj2kzgBri0s'}
- {fliter: 'personal',  video-id: 'pQN6LOOqJ7g'}
- {fliter: 'personal',  video-id: 'tvvBZUwAcbo'}
- {fliter: 'personal',  video-id: 'e8wsfvgAG0A'}
- {fliter: 'personal',  video-id: '7CJwb8FqaMs'}
- {fliter: 'personal',  video-id: 'qeTs05gFkT0'}
- {fliter: 'personal',  video-id: '2VHgpHHtW_U'}

#------------------------------
# Contact

contact-header: Contact me

contact-name:
  data-error: Pleaase enter your name.
  placeholder: Name *

contact-email:
  data-error: Please make sure your email is either vaild or is filled in.
  placeholder: E-mail *

contact-packages-header: Which package do you want?

contact-packages:
  - {checkbox-number: '1', name: basic-videos-option, description: 'Basic Package - If you ever need subtitling, some text work or in general simpler effects for a music video, the price is $10 per min! ($6/hr rate)', checked: checked }
  - {checkbox-number: '2', name: advanced-videos-option, description: 'Advanced Package - I will be helping you produce a music video that is strongly based on some Motion Graphics, Typography, 3D Camera Work, Color Grading and much more. It depends on your approach, it can go $60 per min ($10/hr rate)', checked: }
  - {checkbox-number: '3', name: baschorusc-videos-option, description: 'Chorus MV Package - It would be on a fixed number which is $35 per min!', checked: }

contact-details:
  header: Any more details or info you want to add?
  name: Details
  placeholder: Details

contact-message:
  name: Message
  placeholder: Message

#------------------------------
# Social Icons and URls

social:
  - {icon: 'fa-youtube-play', class: 'youtube-color youtube-color_border', url: 'https://www.youtube.com/AlanCrytex'}
  - {icon: 'fa-twitter', class: 'twitter-color twitter-color_border', url: 'https://twitter.com/Alanj2007Games'}

social-url:
  youtube: https://www.youtube.com/AlanCrytex
  twitter: https://twitter.com/Alanj2007Games
#-------------------------------
# Modified Date

modified-date: September 25, 2017

#-------------------------------
